import { Button } from '@/components/Button/Button';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';
import Router from 'next/router';
import { useState } from 'react';

const baseUrl = process.env.NEXT_PUBLIC_API_URL;

const registerHandler = async (event: any) => {
  event.preventDefault();
  const username = event.target.username.value;
  const name = event.target.name.value;
  const password = event.target.password.value;

  const res = await fetch(`${baseUrl}/users/register`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: '*/*',
      'Accept-Encoding': 'gzip, deflate, br',
      Connection: 'keep-alive',
    },
    body: JSON.stringify({ name, username, password }),
  });

  const result = await res.json();

  return result;
};


export default function Register() {
  const [fail, setFail] = useState(false);

  return (
      <>
        <Head>
          <title>Nýskráning</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta charSet="utf-8"></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.loginForm}>

            <h1>Nýskráning</h1>
            <form className={styles.form}
              onSubmit={async (event) => {
                event.preventDefault();
                const userInfo = await registerHandler(event);
                if (userInfo.username !== undefined) {
                  setFail(false);
                  Router.push('/login');
                } else {
                  setFail(true);
                }
              }}
            >
              <label htmlFor='username'>Notendanafn:</label>

              <input type='text' id='username' required/>

              <label htmlFor='username'>Nafn:</label>

              <input type='text' id='name' required/>

              <label htmlFor='password'>Lykilorð:</label>

              <input type='password' id='password' required/>
              
              {fail ? <p>Ógilt lykilorð/password</p> : <p></p>}
              <Button type='submit'>Nýskrá</Button>
            </form>

          </div>
        </main>
      </>
  )
    
}